import {
  ShoppingCart,
  UtensilsCrossed,
  SprayCan,
  Home,
  Lightbulb,
  Wifi,
  TrainFront,
  Film,
  Palette,
  Shirt,
  Gift,
  Stethoscope,
  Package,
  Coffee,
  Apple,
  Beer,
  Cake,
  CookingPot,
  Sofa,
  BedDouble,
  Key,
  Flame,
  Droplets,
  Zap,
  Plug,
  Smartphone,
  Phone,
  Globe,
  Monitor,
  Car,
  Bus,
  Bike,
  Plane,
  Fuel,
  Music,
  Gamepad2,
  Tv,
  Ticket,
  Camera,
  BookOpen,
  Pen,
  Dumbbell,
  Glasses,
  Watch,
  Gem,
  Sparkles,
  Scissors,
  Heart,
  Users,
  PartyPopper,
  Wine,
  Pill,
  HeartPulse,
  Baby,
  GraduationCap,
  Book,
  Pencil,
  Wallet,
  CreditCard,
  Banknote,
  Coins,
  PiggyBank,
  Receipt,
  Tag,
  Folder,
  Star,
  Bookmark,
  ShoppingBag,
  CircleDot,
  Wrench,
  Mic,
  Landmark,
  Briefcase,
  Laptop,
  PawPrint,
  Flower2,
  Sprout,
  Cross,
  type LucideIcon,
} from "lucide-react";

export type { LucideIcon };

export const ICON_MAP: Record<string, LucideIcon> = {
  "shopping-cart": ShoppingCart,
  "utensils-crossed": UtensilsCrossed,
  "spray-can": SprayCan,
  home: Home,
  lightbulb: Lightbulb,
  wifi: Wifi,
  "train-front": TrainFront,
  film: Film,
  palette: Palette,
  shirt: Shirt,
  gift: Gift,
  stethoscope: Stethoscope,
  package: Package,
  coffee: Coffee,
  apple: Apple,
  beer: Beer,
  cake: Cake,
  "cooking-pot": CookingPot,
  sofa: Sofa,
  "bed-double": BedDouble,
  key: Key,
  flame: Flame,
  droplets: Droplets,
  zap: Zap,
  plug: Plug,
  smartphone: Smartphone,
  phone: Phone,
  globe: Globe,
  monitor: Monitor,
  car: Car,
  bus: Bus,
  bike: Bike,
  plane: Plane,
  fuel: Fuel,
  music: Music,
  "gamepad-2": Gamepad2,
  tv: Tv,
  ticket: Ticket,
  camera: Camera,
  "book-open": BookOpen,
  pen: Pen,
  dumbbell: Dumbbell,
  glasses: Glasses,
  watch: Watch,
  gem: Gem,
  sparkles: Sparkles,
  scissors: Scissors,
  heart: Heart,
  users: Users,
  "party-popper": PartyPopper,
  wine: Wine,
  pill: Pill,
  "heart-pulse": HeartPulse,
  baby: Baby,
  "graduation-cap": GraduationCap,
  book: Book,
  pencil: Pencil,
  wallet: Wallet,
  "credit-card": CreditCard,
  banknote: Banknote,
  coins: Coins,
  "piggy-bank": PiggyBank,
  receipt: Receipt,
  tag: Tag,
  folder: Folder,
  star: Star,
  bookmark: Bookmark,
  "shopping-bag": ShoppingBag,
  "circle-dot": CircleDot,
  wrench: Wrench,
  mic: Mic,
  landmark: Landmark,
  briefcase: Briefcase,
  laptop: Laptop,
  "paw-print": PawPrint,
  "flower-2": Flower2,
  sprout: Sprout,
  cross: Cross,
};

export const DEFAULT_ICON = "package";

export function getIconComponent(name: string): LucideIcon {
  return ICON_MAP[name] ?? ICON_MAP[DEFAULT_ICON];
}

export type IconCategory = {
  label: string;
  icons: string[];
};

export const ICON_CATEGORIES: IconCategory[] = [
  {
    label: "食事",
    icons: [
      "shopping-cart",
      "utensils-crossed",
      "coffee",
      "apple",
      "beer",
      "cake",
      "cooking-pot",
      "wine",
    ],
  },
  {
    label: "住居",
    icons: ["home", "sofa", "bed-double", "key"],
  },
  {
    label: "光熱・通信",
    icons: [
      "lightbulb",
      "flame",
      "droplets",
      "zap",
      "plug",
      "wifi",
      "smartphone",
      "phone",
      "globe",
      "monitor",
      "laptop",
    ],
  },
  {
    label: "交通",
    icons: ["train-front", "car", "bus", "bike", "plane", "fuel"],
  },
  {
    label: "娯楽・趣味",
    icons: [
      "film",
      "palette",
      "music",
      "gamepad-2",
      "tv",
      "ticket",
      "camera",
      "book-open",
      "pen",
      "dumbbell",
      "mic",
    ],
  },
  {
    label: "ファッション",
    icons: ["shirt", "glasses", "watch", "gem", "sparkles", "scissors"],
  },
  {
    label: "人間関係",
    icons: ["gift", "heart", "users", "party-popper", "baby"],
  },
  {
    label: "医療・教育",
    icons: [
      "stethoscope",
      "pill",
      "heart-pulse",
      "cross",
      "graduation-cap",
      "book",
      "pencil",
    ],
  },
  {
    label: "お金",
    icons: [
      "wallet",
      "credit-card",
      "banknote",
      "coins",
      "piggy-bank",
      "receipt",
      "landmark",
      "briefcase",
    ],
  },
  {
    label: "その他",
    icons: [
      "package",
      "tag",
      "folder",
      "star",
      "bookmark",
      "shopping-bag",
      "circle-dot",
      "wrench",
      "paw-print",
      "flower-2",
      "sprout",
    ],
  },
];
